import 'package:bloc/bloc.dart';
import 'package:elbadr_app/models/Product_model.dart';
import 'package:elbadr_app/modules/hanenkrat/cubit/states.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

class HanenkratCubit extends Cubit<HanenkratStates> {
  HanenkratCubit() : super(HanenkratInitialState());

  static HanenkratCubit get(context) => BlocProvider.of(context);
  List<ProductModel> hanenkratProducts = [
    ProductModel('economy', 'assets/images/henenkrat/economy.jpg',
        'High image quality\nBest stability against corrosion\nHigh resistance against disinfection and sterilization'),
    ProductModel(
        'ExaPin-Drillparapulpal-Pin',
        'assets/images/henenkrat/ExaPin-Drillparapulpal-Pin.jpg',
        'ExaPin parapulpal pin made of x-ray visible\nHT-Glassfiber\nDentine preserving and stress-free insertion Due to a dentine similar E-module, a more homogeneous restoration than with a titanium pin can\nbe expected\nEfficient and safe handling Due to a placing part, which can be easily removed by just twisting after the composite is cured'),
    ProductModel('Fiper Post System', 'assets/images/henenkrat/fiber2-2.jpg',
        '\nIn 1995 E. HAHNENKRATT GmbH was the first company offering a root post made of carbon fibre and in 1997 the first one offering glass fibre posts in Germany, followed in 1998 by a root post made of quartz fibre. In 2001 at the IDS in Cologne the new post system CYTEC was presented, which is produced with posts made of HT-carbon or HT glass fibres\nHT means High Tenacity, for highest bending strength and fatigue resistance\nAlso in 2001, the well-tried EXATEC system was completed by root posts made of carbon- and glass-fibre\n\nHigh bending strength\n\nof 1.678 MPa (EN ISO 178) of HT glass fibre that optimizes the stability of the reconstruction\n\nHomogenity of the reconstruction\n\nGlass-fibre posts have an elastic attitude that is more similar to the dentine as i.e. Titanium or Zirconium. Consequently the root post, the composite and the remnant tooth can create a biomechanical homogeneous unit, supporting the stability of the reconstructio\n\nFunctional post design\n\nThe post consists of a cylindrical and a conical apical part. The rounded retentions in the head-section support secure bonding and additionally serve to anti-rotation. In the apial section the spiral escape grooves ensure decompression and retention\n\nMicro retentive surface\n\nAs a result of the micro retentive surface that is structured by fibres no silanisation is necessary\n\nEsthetical restoration\n\nThe white and semi-translucent root posts made of glassfibre offer you the basis for a restoration with fully ceramic crowns'),
    ProductModel('Mirror Handle', 'assets/images/henenkrat/handle.jpg',
        'Made of high quality Stainless Steel\nThe high quality of the material is reflected by the high end finish'),
    ProductModel('Matrix Retainer', 'assets/images/henenkrat/matrix.jpg',
        'matrix retainers are manufactured of Stainless Steel that is resistant against corrosion\nMatrix retainer for Tofflemire-matrixes and matrix bands in dispensers'),
    ProductModel(
        'Mega-FS Rhodium Coated Mirror',
        'assets/images/henenkrat/mega.jpg',
        'good reasons, why you should decide for our MEGA-FS mouth mirrors\n\nSuperior reflection concerning sharpness and contrast\n\nup to the smallest detail, without any distortion\n\nNatural colours and lightness for brilliant image quality\n\nwith an optimal reflection spectrum of 90% in comparison to silver\n\nHighest sight comfort\n\nSimple cleaning\n\ndue to the anti-stick-effect of the Rhodium coating\n\nSilk-matted stainless steel surfac\n\neliminates disturbing reflections and glares\n\nAbsolutly resistent\n\nagainst all kinds of disinfection and sterilisation even agains refresh-products containing acids\n\nComfortable cheek retraction\n\nthrough wide stem design\n\nHygienic\n\nbecause weld-free design, that allows no deposition\n\n\nDue to the Rhodium reflection layer (FS – Front Surface) being directly on the surface the image is reflected only once and therefore exactly sharp\nAs a precious metal, like Gold, Rhodium is resistent against all disinfection product even against those acids used in dentistry, and included in so-called refresh-products, as for example Neodisher N with a 25% share of phosphoric acid'),
    ProductModel('Provisa Temporary shells', 'assets/images/henenkrat/provisa.jpg', 'Temporary shells are the cheapest possibility to manufacture an individual temporary measure. The shells consist of nickel-free Aluminium and Tin foil. Both materials are tested for bio-compatibility according to ISO 10993 Biological evaluation of medical devices\n The occlusal surface is modelled by closing jaws to a biting position, bringing to occlusion and the shape remains stable after the polymerisation of the temporary cement\n\n The individual preparation\n\nThe individual preparation and adaption is time saving, simple and a million times exprienced and is made analogous to the procedure to the dental care by the use of a temporary crown\ninitial situation: prepared tooth stump\nselection of a fitting size by the help of a dentimeter ring\ncontouring of the temporary crown\nPolishing of the edges with a polishing rubber\nFinal prepared temporary crown\nFinal prepared temporary crown inserted with a temporary cement'),
    ProductModel(
        'Pullover Retraction tube', 'assets/images/henenkrat/pullover.jpg', 'The »PULLover« is a stretchabel tube, which just needs to be pulled over the tooth stump\n\nhandy and efficient\n\nThe »PULLover« Retraction Tube is easy and time-saving to fit and thus highly efficient\n\noutstanding absorptive\n\nThe tissue is made out of specially treated fibers, providing a high capacious suction power. The meshes function as pores, which improve -with their capillary action- the suction power.\n\nimproved position stability in the sulcus\n\nThanks to the elasticity, the »PULLover« provides an improved position stability'),
    ProductModel(
        'RELAX Front Surface Mouth Mirrors',
        'assets/images/henenkrat/relax-1.jpg',
        'RELAX – designed with a perfect blend of ­\nechnology and ergonomics\nThe advantages of a front surface mirror in combination with the »lite« fiberglass design, provide highest ­comfort for you and your patient for relaxed dental ­operations\nThe instrument is autoclavable, acid-resistant and suitable for thermal disinfecotrs\n\ncomfortably light weight\n\nfor relaxed dental operations\n\ncomfortable to hold\n\ndue to the ergonomic design with grip recess\n\nkeeping quality\n\ncolour stable, resistant against acids as well as against plaque-indicators\n\ncomfortable for patients\n\ndue to the smooth finish\n\nhygienic\n\ndue to the plane transition from mirror surface to mirror casing without any gap\n\nsilk-mat-finished\n\nreflectionfree surface'),
    ProductModel('Sharp Cut crown cutters', 'assets/images/henenkrat/sharp.jpg', 'SHARPcut Crown Removers are dedicated (suitable) – by their optimized criss-cross cutting parts – for all metal alloys, for titanium as well as for composite veneers\n\nThe features are\n\nMinimized risk of fracture\noptimized cutting characteristics\nby optimized criss-cross cutting parts\nas high material reduction\nminimized vibration\nlongterm performance\n\nThe result are\n\nHigh material reduction\nMinimized vibration\nLong term performance\nEasy penetration due to transversal blades on the tip'),
    ProductModel(
        'Exatec Titanium Root post system', 'assets/images/henenkrat/titanium-s.jpg', '\nA root post which is conical shaped in its apical section, has many advantages over cylindrical posts\n\nDue to the fact that the conical shape corresponds to the natural course of the dental roots, it is ensured that more tooth mass is preserved in the critical area of the root tip, thus minimising the risk of a root fracture\nAt the junction of the post and head that is potentially at risk of fracture, the conical Exatec post has rounded transitions and a larger post cross-section than a cylindrical post at the same apical lenght. The Exatec post is therefore more stable and achieves better scores and bending load tests.\nHowever, conical posts must be surely anchored without wedge reaction. Therefore the Exatec-Calibriation drill was developed. This special drill prepares a precise axial lug-rest for the Exatec posthead, that automatically determines the position in which the post has dentine contact, but exerts no pressure on the root wall\nThe posthead fits exactly into the calibrated post bearing. Thus the stability of the restoration is optimised and the apical upward movement of the post is stopped with precision. Because of the conus the highest possible preservation of the tooth substance is achieved\n\nFor a perfect and precise restoration an instrument is necessary, that guarantees a perfect fit of drilling and post\n\nExatec-Calibribration Drill\n\nwith integrated head cutter that calibrates the axial support of the post in a single pass\n\nThe perfect support\n\nensures the axial support of the post head into the dentine'),
    ProductModel(
        'Ultra-Fs Brightest Front Surface Mirror',
        'assets/images/henenkrat/ultra.jpg',
        '\nULTRA FS – the brightest and sharpest mirror worldwide\n\nThe new unique design of the mirror layers provides superior bright images and clarity previously unavailable\n\nThe features are\n\nWith about 113% reflection factor, this ULTRA FS mirror is even brighter than Rhodium\nSuperior colour accuracy\nExact sharpness\nScratch resistant\nImproved comfortable cheek retraction'),
  ];
}
