import 'package:bloc/bloc.dart';
import 'package:elbadr_app/models/Product_model.dart';
import 'package:elbadr_app/modules/zumax/cubit/states.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

class ZumaxCubit extends Cubit<ZumaxStates> {
  ZumaxCubit() : super(ZumaxInitialState());

  static ZumaxCubit get(context) => BlocProvider.of(context);
  List<ProductModel> zumaxProducts = [
    ProductModel('HL-8200 Head Light', 'assets/images/zumax/head-light-8200.jpg', 'Light Source: Our LED lamp without the heat of traditional Halogen headlight. With a color temperature of 5500 Kelvin, this light supplies bright, white, shadow-free light allowing the doctor to see tissure characeristics without distortion\nHomogenous illumination of the whole field of view\nEnjoy the flexibility of operating the headlight using the rechargeable lithium battery, can use without the direct power source. It is one of most comfortable light weight headlights and suitable for all kinds of surgery\nThe headlight can be used when it is charging\nHas low-battery indicator light\nOptional adapts to any Binocular Loupes of Zumax, Gallilei, Zeiss, Orascophic TTL and Flip up, Grendel Meier and Heine\nYellow filter reduces blue light, prevents premature curing of composite\nSmart design, convenient for mobile diagnosis\nIllumination in 200mm working distance: =35000 Lx\nAdjustable range\nFluctuation distance: 12.5mm\nDirection of Illumination: Vertical ± 25° Adjustable\nLightest weight for Head lamp: 21g\nIllumination Source: Extremely bright light, 3W LED. Life 20,000 hours continuous burn, Battery Run-time: >6 hours'),
    ProductModel('HL-8300 Head Light', 'assets/images/zumax/head-light-8300.jpg', 'Light Source: Our LED lamp without the heat of traditional Halogen headlight. With a color temperature of 5500 Kelvin, this light supplies bright, white, shadow-free light allowing the doctor to see tissure characeristics without distortion\nHomogenous illumination of the whole field of view\nEnjoy the flexibility of operating the headlight using the rechargeable lithium battery, can use without the direct power source. It is one of most comfortable light weight headlights and suitable for all kinds of surgery\nThe headlight can be used when it is charging\nHas low-battery indicator light\nOptional adapts to any Binocular Loupes of Zumax, Gallilei, Zeiss, Orascophic TTL and Flip up, Grendel Meier and Heine\nYellow filter reduces blue light, prevents premature curing of composite\nSmart design, convenient for mobile diagnosis\nElectrical Safety Standard: IEC60601.1 class II Type BF equipment\nIllumination in 200mm working distance: =35000 Lx\nAdjustable range\nFluctuation distance: 12.5mm\nDirection of Illumination: Vertical ± 25° Adjustable\nLightest weight for Head lamp: 21g\nIllumination Source: Extremely bright light, 3W LED. Life 20,000 hours continuous burn, Battery Run-time: >6 hours'),
    ProductModel('Ohl-8000-1', 'assets/images/zumax/hl-8000-1.jpg', 'Optical specifications\n\n\nDiameter of the light spot at a distance of 420mm: 20-80mm\nIllumination in 200mm working distance >50000 Lx\nAdjustable range\nFluctuation distance: 12.5mm\nVertical direction of Illumination:±25°adjustable\nNet Weight\n69g  excluding headband\nElectrical specifications\nIllumination Source: extremely bright light, 5W LED. Life 20000 hours continuous burn\nBattery: 7.4V Lithium battery rechargeable, Run-time: >7 hours\nMaximum Power input: 15VA\nElectrical Safety Standard: IEC60601.1 class II Type BF equipment\nLight Source: Our LED lamp without the heat of traditional Halogen headlight. With a color temperature of 5000 Kelvin, this light supplies bright, white, shadow-free light allowing the doctor to see tissue characteristics without distortion\nEnjoy the flexibility of operating the headlight using the rechargeable Lithium battery, can use without the direct power source. It is one of the most comfortable lightweight headlights and suitable for all kinds of surgery\nThe headlight could be used when it is charging. Has low-battery indicator light\nAdapts to any Binocular Loupes of Zumax\nSmart design, convenient for mobile diagnosis'),
    ProductModel('Zumax Microscope', 'assets/images/zumax/microscope9.jpg', 'Basic configuration:\nMagnification system: 6 step manual magnification changer Y=0.33x, 0.5x, 0.8x, 1.22x, 2x, 3x\nTubes: 0-180 inclinable binocular tube, f=170mm\nEyepieces: 12.5x wide field eyepieces also suitable for eyeglass wearers\nFocus: F=250mm with fine focus, fine focusing range 12mm\nIllumination system: integrated led illumination, >70, 000Lx field of view diameter 80mm with f=250mm objective lens,\nYellow and green integrated filter\nHandgrip: Rotatable handgrip & T-handgrip\nBeam Splitter\nDSLR Camera adapter\nConstruction: Floor stand with “H” shaped base\n\nOptional:\n\nVarioDist Lens 190:300mm\n0-180 inclinable binocular tube with PD adjusting knob\nBalancing arm\n30 Binocular extender and beam splitter\nRotation Ring\nBuilt-in HD camera system\nMobile adapter & Mobil adapter plus\nWireless shutter foot control for DSLR camera\nMicro 3D integrated\nFlash adapter for DSLR camera'),
    ProductModel('Zumax Broken Instrument Removal Kit', 'assets/images/zumax/retrival-kit.jpg', 'Instrument separation is one of the most common complications in root canal treatment process. The innovative design of instrument separation removal kit changes the traditional clinical methods. This design makes instrument separation removal process quick and easy\n\nAdvantages\n\n\nLimited amount of removed dentin of root canal wall\nAvoid the inconvenience and risk of the ultrasonic tip fracture in traditional technique\nAvoid secondary fracture of the separated nickel titanium instrument when using the ultrasonic technique\nMicroscopic tweezers are favorable and efficient for operation\nThe operation process is easy to learn and use'),
    ProductModel('SLF Flip-Up Binocular Loupes', 'assets/images/zumax/SLF-2.jpg', 'SLF series Binocular Loupes is designed for all possible medical needs\nFeatures\n\nMulti-coated, high grade glass lenses produce crisp, clear image\nThe Loupes which employ eyepiece of very large view field diameter. The depth of focus is deep and object can be seen stereoscopically with actual distance feeling\nThe angle of the loupes can be adjusted between 0 ~40 with ease and fatigue is minimized even after prolonged use\n6mm up and down displacement. Pupil distance can be adjusted individually which could be suited for all kind of faces\nAdapts to any Headband and Headlight of Zumax\nSmart design, convenient for mobile diagnosis\nVertical distance: 6mm\nAdjustable viewing angle: 0 ~40\nAdjustable pupil distance: 45mm/1.6”~80mm/3.1”\n2.5x is the most popular model. It offers the widest field of view and longest depth of focus\n3.0x is designed for dentists who need more magnigication, which give you good field of view and depth of focus\n3.5x is the highest magnification available in Galilean Loupes, being suitable for specialist work within a smaller depth of view, and allows you to perform most dental procedures, such like cosmetic, crown and bridge etc'),
    ProductModel('SLH Binocular Loupes', 'assets/images/zumax/SLH-1.jpg', 'SLH series Binocular Loupes is designed for all possible medical needs\nFeatures\n\nMulti-coated, high grade glass lenses produce crisp, clear image\nThe Loupes which employ eyepiece of very large view field diameter. The depth of focus is deep and object can be seen stereoscopically with actual distance feeling\nThe angle of the loupes can be adjusted between 0 ~40 with ease and fatigue is minimized even after prolonged use\n6mm up and down displacement. Pupil distance can be adjusted individually which could be suited for all kind of faces\nAdapts to any Headband and Headlight of Zumax\nSmart design, convenient for mobile diagnosis\nVertical distance: 6mm\nAdjustable viewing angle: 0 ~40\nAdjustable pupil distance: 45mm/1.6”~80mm/3.1”\n2.5x is the most popular model. It offers the widest field of view and longest depth of focus\n3.0x is designed for dentists who need more magnigication, which give you good field of view and depth of focus\n3.5x is the highest magnification available in Galilean Loupes, being suitable for specialist work within a smaller depth of view, and allows you to perform most dental procedures, such like cosmetic, crown and bridge etc'),
    ProductModel('SLT Custom Made Binocular Loupes', 'assets/images/zumax/ttl2.jpg', 'Magnification Available 2.5 and 3.0x\nExtremely high resolution\nPrecision Optics\nCustom Fit and Custom Working Distance\nGreatest Brightness and Depth of Field\nUltra-lightweight, as little as 2 oz.(57g) including the frame\nAll lenses are muti-coated and anti-reflective, combining with infinity corrected optical system\n\nTwo kinds of frames for your option which provides the best comfort at work\nSport Frame, three colors for your optional –\nAluminium magnesium alloy Frame –\nSoft silicone nose pad\nAll loupes include a protective hard case, microfiber wipe cloth, neck strap'),

  ];
}
