import 'package:bloc/bloc.dart';
import 'package:elbadr_app/models/Product_model.dart';
import 'package:elbadr_app/modules/Zafdent_Screen/cubit/states.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

class ZafDentCubit extends Cubit<ZafDentStates> {
  ZafDentCubit() : super(ZafDentInitialState());

  static ZafDentCubit get(context) => BlocProvider.of(context);
  List<ProductModel> zafDentProducts = [
    ProductModel(
        'A New Unit', 'assets/images/zafdent/anewunit.jpg', 'Luxory 24V DC Denmark motor chair control system\n with 9 memories working status LCD display\n Spitton cabinet can move laterally 45 degree\n Tunable high-grade LED operating light\n Deluxe removable Glass spittoon\n Import electromagnetism valve\n Plastic frame with two colour\n Built-in tissue box\n Natural Leather\n cup automatic quantitative water supply system gargle\n multi-function foot control\n strong, weak a saliva suction system\n three with spray gun hot and cold\n disposable cup holder\n glass tray\n Dentist stool 2Pcs A&C'),
    ProductModel('A Unit', 'assets/images/zafdent/aunit.jpg',
        'Luxory 24V DC Denmark motor chair control system\n with 9 memories working status LCD display\n Spitton cabinet can move laterally 45 degree\n Tunable high-grade LED operating light\n Deluxe removable ceramic spittoon\n Import electromagnetism valve\n Plastic frame with two colour\n Built-in tissue box\n Natural Leather\n cup automatic quantitative water supply system gargle\n multi-function foot control\n strong, weak a saliva suction system\n three with spray gun hot and cold\n disposable cup holder\n glass tray'),
    ProductModel('B New Unit', 'assets/images/zafdent/bnewunit.jpg',
        'Deluxe removable cleaning glass spittoon\n Glass plate\n Cup holder\n Built-in tissue box\n Button protective plastic cover\n Tunable high-grade LED operating light light\n Auto spitton flush and cup filler control system\n high-grade articulated headrest\n 24V noiseless DC motor\n Air brake instrument try\n Saliva ejector with high and low suction\n 3-way syringe\n Anti rust body\n LED x-film viewer\n Dentist Stool A\n Full function foot control'),
    ProductModel('C Unit', 'assets/images/zafdent/cunit.jpg',
        'STANDARD ACCESSORIES\n Tempered ceramic spittoon\n Button protective plastic cover\n Adjustable operating light\n Auto spitton flush and cup fillercontrol system\n high-grade articulated headrest\n 24V noiseless DC motor\n Air brake instrument try\n Saliva ejector with high and low suction\n 3-way syringe\n Anti rust body\n LED x-film viewer\n Dentist Stool A'),
    ProductModel('D Unit', 'assets/images/zafdent/dunit.jpg',
        'with a nine bit memory a electric dental chair\n deluxe ceramic spittoon\n Built-in Tissue Box\n Button protective plastic cover\n Tunable high-grade LED operating light light\n Auto spitton flush and cup filler control system\n high-grade articulated headrest\n 24V noiseless Denmark DC motor\n Air brake instrument try\n Saliva ejector with high and low suction\n 3-way syringe\n Anti rust body\n LED x-film viewer\n Dentist Stool A\n Full function foot control'),
    ProductModel('F New Unit', 'assets/images/zafdent/fnewunit.jpg',
        'deluxe removable cleaning ceramic spittoon\n Button protective plastic cover\n with a three bit memory a electric dental chair\n Tunable high-grade LED operating light light\n Auto spitton flush and cup filler control system\n high-grade articulated headrest\n 24V noiseless Denmark DC motor\n Air brake instrument try\n Saliva ejector with high and low suction\n 3-way syringe\n Anti rust body\n LED x-film viewer\n Dentist Stool A\n Full function foot control'),
    ProductModel('F Unit', 'assets/images/zafdent/funit.jpg',
        'deluxe removable cleaning ceramic spittoon\n water air electric integration master valve\n separately Cup holder and wipes\n Button protective plastic cover\n Tunable high-grade LED operating light light\n Auto spitton flush and cup filler control system\n high-grade articulated headrest\n 24V noiseless DC motor\n Air brake instrument try\n Saliva ejector with high and low suction\n 3-way syringe\n Anti rust body\n LED x-film viewer\n Dentist Stool A\n Full function foot control\n Avaliable For Left Hand Dentist'),
    ProductModel('Q 5 Unit', 'assets/images/zafdent/q5unit.jpg',
        '  lateral horizontal movement 45 degree \n  Highly-fit compensating chair frame\n  Soft super-thin seamless leather\n  Douable-track silent sliding\n  luxory Denmark motor chair control system\n  with 9 memories Working status LCD display\n  Panorama LED X-film viewer\n  Dentist Stool 2Pcs A&C\n  Built-in LCD holder\n  Tunable high-grade LED Operating light 10-Bulb\n  Rotatable & Removable cleaning ceramic spitton\n  outer floor box with main switch\n  Import electromagnetism valve\n  2-water storage bottles\n  Built-in LCD holder\n  Natural Leather\n  cup automatic quantitative water supply system gargle\n  multi-function foot contrlol with self lock\n  strong, weak a saliva suction system\n  three with spray gun hot and cold\n  disposable cup holder\n  glass tray'),
    ProductModel('Q 1 Unit', 'assets/images/zafdent/qoneunit.jpg',
        'Side cabinet can move 180 degree to support Left and Right hand dentists\n Independent movable instrument tray Working status LCD display\n Luxory Denmark motor chair control system with 9 memories\n Tunable high-grade LED Operating light 10-Bulb\n Rotatable & Removable cleaning ceramic spitton\n Build in floor box with main switch\n Import electromagnetism valve\n Panoramic LED X-film viewer\n Dentist Stool 2Pcs A&C\n 2-water storage bottles\n Built-in LCD holder\n Built-in tissue box\n Natural Leather\n cup automatic quantitative water supply system gargle\n multi-function foot control\n strong, weak a saliva suction system\n three with spray gun hot and cold\n disposable cup holder\n glass tray'),
    ProductModel('Q 2 Unit', 'assets/images/zafdent/qtwounit.jpg',
        'Luxory Denmark motor chair control system\nwith 9 memories Working status LCD display\nSpitton cabinet can move laterally 45 degree\n Panorama LED X-film viewer\n Dentist Stool 2Pcs A&C\n Built-in LCD holder\n Tunable high-grade LED Operating light 10-Bulb\n Rotatable & Removable cleaning ceramic spitton\n outer floor box with main switch\n Import electromagnetism valve\n 2-water storage bottles\n Built-in LCD holder\n Natural Leather\n cup automatic quantitative water supply system gargle\n multi-function foot contrlol with self lock\n strong, weak a saliva suction system\n three with spray gun hot and cold\n disposable cup holder\n glass tray'),
  ];
}
